apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accio

resources:
  - infrastructure.yaml
  - services/envoy-gateway.yaml
  - services/auth-service.yaml
  - services/catalog-service.yaml
  - services/provisioner-service.yaml
  - services/scorecard-service.yaml
  - services/workflow-service.yaml
  - services/audit-service.yaml
  - services/portal-ui.yaml