apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accio

resources:
  - ../../base

images:
  - name: catalog-service
    newName: <ECR_PLACEHOLDER>.dkr.ecr.us-east-1.amazonaws.com/catalog-service
    newTag: v1.0.0
  - name: provisioner-service
    newName: <ECR_PLACEHOLDER>.dkr.ecr.us-east-1.amazonaws.com/provisioner-service
    newTag: v1.0.0
  - name: scorecard-service
    newName: <ECR_PLACEHOLDER>.dkr.ecr.us-east-1.amazonaws.com/scorecard-service
    newTag: v1.0.0
  - name: workflow-service
    newName: <ECR_PLACEHOLDER>.dkr.ecr.us-east-1.amazonaws.com/workflow-service
    newTag: v1.0.0
  - name: audit-service
    newName: <ECR_PLACEHOLDER>.dkr.ecr.us-east-1.amazonaws.com/audit-service
    newTag: v1.0.0
  - name: portal-ui
    newName: <ECR_PLACEHOLDER>.dkr.ecr.us-east-1.amazonaws.com/portal-ui
    newTag: v1.0.0
  - name: auth-service
    newName: <ECR_PLACEHOLDER>.dkr.ecr.us-east-1.amazonaws.com/auth-service
    newTag: v1.0.0

commonLabels:
  variant: prod

replicas:
  - name: catalog-service
    count: 2
  - name: provisioner-service
    count: 2
  - name: scorecard-service
    count: 2
  - name: workflow-service
    count: 2
  - name: audit-service
    count: 2
  - name: portal-ui
    count: 2
  - name: auth-service
    count: 2