apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: {{ include "Strata.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auditService.service.port }}
      targetPort: {{ .Values.auditService.service.port }}
  selector:
    app: audit-service