apiVersion: v1
kind: Service
metadata:
  name: portal-ui
  namespace: {{ include "Strata.namespace" . }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.portalUi.service.port }}
      targetPort: {{ .Values.portalUi.service.port }}
      nodePort: {{ .Values.portalUi.service.nodePort }}
  selector:
    app: portal-ui