apiVersion: v1
kind: Service
metadata:
  name: provisioner-service
  namespace: {{ include "Strata.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.provisionerService.service.port }}
      targetPort: {{ .Values.provisionerService.service.port }}
  selector:
    app: provisioner-service