apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-engine
  namespace: {{ include "Strata.namespace" . }}
spec:
  replicas: {{ .Values.workflowEngine.replicaCount }}
  selector:
    matchLabels:
      app: workflow-engine
  template:
    metadata:
      labels:
        app: workflow-engine
    spec:
      containers:
        - name: workflow-engine
          image: "{{ .Values.workflowEngine.image.repository }}:{{ .Values.workflowEngine.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.workflowEngine.service.port }}
          env:
            - name: DB_DSN
              value: {{ include "Strata.postgres.url" . }}
            - name: NATS_URL
              value: {{ include "Strata.nats.url" . }}
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: PORT
              value: {{ .Values.workflowEngine.service.port | quote }}
          resources:
            {{- toYaml .Values.workflowEngine.resources | nindent 10 }}