apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: {{ include "Strata.namespace" . }}
spec:
  serviceName: nats-headless
  replicas: {{ .Values.nats.replicaCount }}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args: ["-js"]
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitoring
          resources:
            {{- toYaml .Values.nats.resources | nindent 10 }}