name: observatory
description: Strata Platform — Observatory Flutter Web App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Auth
  amazon_cognito_identity_dart_2: ^3.8.1

  # HTTP
  http: ^1.2.0

  # Fonts & UI
  google_fonts: ^6.2.1

  # State management
  provider: ^6.1.2

  # Utils
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
