apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: accio
spec:
  serviceName: nats-headless
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10-alpine
          args: ["-js"]
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitoring
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  namespace: accio
spec:
  clusterIP: None
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222
  selector:
    app: nats
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: accio
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222
  selector:
    app: nats