apiVersion: v1
kind: Secret
metadata:
  name: authelia-secret
  namespace: accio
type: Opaque
stringData:
  AUTHELIA_AUTHENTICATION_BACKEND_JWT_SECRET: acciodevsecret
  AUTHELIA_SESSION_SECRET: acciodevsecret
  AUTHELIA_NOTIFIER_SECRET: acciodevsecretacciodevsecret1234