apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: {{ include "Strata.namespace" . }}
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "Strata.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres