apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: {{ include "accio.namespace" . }}
  labels:
    {{- include "accio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.auditService.service.port }}
      targetPort: {{ .Values.auditService.service.port }}
  selector:
    {{- include "accio.selectorLabels" . | nindent 4 }}
    component: audit-service