apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-ui
  namespace: {{ include "accio.namespace" . }}
spec:
  replicas: {{ .Values.portalUi.replicaCount }}
  selector:
    matchLabels:
      app: portal-ui
  template:
    metadata:
      labels:
        app: portal-ui
    spec:
      containers:
        - name: portal-ui
          image: "{{ .Values.portalUi.image.repository }}:{{ .Values.portalUi.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.portalUi.service.port }}
          env:
            - name: VITE_CATALOG_URL
              value: "http://catalog-service:{{ .Values.catalogService.service.port }}"
            - name: VITE_PROVISIONER_URL
              value: "http://provisioner-service:{{ .Values.provisionerService.service.port }}"
            - name: VITE_SCORECARD_URL
              value: "http://scorecard-service:{{ .Values.scorecardService.service.port }}"
            - name: VITE_WORKFLOW_URL
              value: "http://workflow-engine:{{ .Values.workflowEngine.service.port }}"
            - name: VITE_AUDIT_URL
              value: "http://audit-service:{{ .Values.auditService.service.port }}"
            - name: VITE_AUTH_URL
              value: "http://auth-service:8086"
          resources:
            {{- toYaml .Values.portalUi.resources | nindent 10 }}