apiVersion: v1
kind: Service
metadata:
  name: portal-ui
  namespace: {{ include "accio.namespace" . }}
  labels:
    {{- include "accio.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.portalUi.service.port }}
      targetPort: {{ .Values.portalUi.service.port }}
      nodePort: {{ .Values.portalUi.service.nodePort }}
  selector:
    {{- include "accio.selectorLabels" . | nindent 4 }}
    component: portal-ui