apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner-service
  namespace: {{ include "accio.namespace" . }}
spec:
  replicas: {{ .Values.provisionerService.replicaCount }}
  selector:
    matchLabels:
      app: provisioner-service
  template:
    metadata:
      labels:
        app: provisioner-service
    spec:
      containers:
        - name: provisioner-service
          image: "{{ .Values.provisionerService.image.repository }}:{{ .Values.provisionerService.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.provisionerService.service.port }}
          env:
            - name: DB_DSN
              value: {{ include "accio.postgres.url" . }}
            - name: NATS_URL
              value: {{ include "accio.nats.url" . }}
            - name: PORT
              value: {{ .Values.provisionerService.service.port | quote }}
          resources:
            {{- toYaml .Values.provisionerService.resources | nindent 10 }}