apiVersion: v1
kind: Service
metadata:
  name: workflow-engine
  namespace: {{ include "accio.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.workflowEngine.service.port }}
      targetPort: {{ .Values.workflowEngine.service.port }}
  selector:
    app: workflow-engine