{{- /*
Nats headless and clusterip services
*/ -}}
---
apiVersion: v1
kind: Service
metadata:
  name: nats-headless
  namespace: {{ include "accio.namespace" . }}
  labels:
    {{- include "accio.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222
  selector:
    {{- include "accio.selectorLabels" . | nindent 4 }}
    component: nats
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{ include "accio.namespace" . }}
  labels:
    {{- include "accio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitoring
      port: 8222
      targetPort: 8222
  selector:
    {{- include "accio.selectorLabels" . | nindent 4 }}
    component: nats