namespace: accio

global:
  imagePullPolicy: IfNotPresent
  imageTag: latest

ingress:
  enabled: false
  className: ""
  annotations: {}

postgres:
  replicaCount: 1
  image:
    repository: postgres
    tag: "15-alpine"
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 128Mi
  storage: 1Gi
  env:
    user: accio
    database: accio
    password: accio_password

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: "7-alpine"
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 64Mi

nats:
  replicaCount: 1
  image:
    repository: nats
    tag: "2.10-alpine"
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 128Mi

authService:
  replicaCount: 1
  image:
    repository: auth-service
    tag: latest
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 64Mi

catalogService:
  replicaCount: 1
  image:
    repository: catalog-service
    tag: latest
  service:
    port: 8081
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 64Mi

provisionerService:
  replicaCount: 1
  image:
    repository: provisioner-service
    tag: latest
  service:
    port: 8082
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 64Mi

scorecardService:
  replicaCount: 1
  image:
    repository: scorecard-service
    tag: latest
  service:
    port: 8083
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 64Mi

workflowEngine:
  replicaCount: 1
  image:
    repository: workflow-engine
    tag: latest
  service:
    port: 8084
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 64Mi

auditService:
  replicaCount: 1
  image:
    repository: audit-service
    tag: latest
  service:
    port: 8085
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 64Mi

portalUi:
  replicaCount: 1
  image:
    repository: portal-ui
    tag: latest
  service:
    port: 3000
    nodePort: 30000
  resources:
    limits:
      cpu: "0.5"
      memory: 256Mi
    requests:
      cpu: "0.1"
      memory: 64Mi