apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accio

resources:
  - ../../base

patches:
- path: patches/image-pull-secret.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    namespace: accio

images:
  - name: catalog-service
    newName: ${ECR_REGISTRY}.dkr.ecr.ap-south-1.amazonaws.com/accio/catalog-service
    newTag: ${IMAGE_TAG}
  - name: provisioner-service
    newName: ${ECR_REGISTRY}.dkr.ecr.ap-south-1.amazonaws.com/accio/provisioner-service
    newTag: ${IMAGE_TAG}
  - name: scorecard-service
    newName: ${ECR_REGISTRY}.dkr.ecr.ap-south-1.amazonaws.com/accio/scorecard-service
    newTag: ${IMAGE_TAG}
  - name: workflow-service
    newName: ${ECR_REGISTRY}.dkr.ecr.ap-south-1.amazonaws.com/accio/workflow-service
    newTag: ${IMAGE_TAG}
  - name: audit-service
    newName: ${ECR_REGISTRY}.dkr.ecr.ap-south-1.amazonaws.com/accio/audit-service
    newTag: ${IMAGE_TAG}
  - name: portal-ui
    newName: ${ECR_REGISTRY}.dkr.ecr.ap-south-1.amazonaws.com/accio/portal-ui
    newTag: ${IMAGE_TAG}
  # - name: auth-service
  #   newName: localhost:5000/auth-service
  #   newTag: ebd9b0dc1b865f3e2fe4f55a52187c82618cd9ea
