apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configmap
  namespace: {{ include "accio.namespace" . }}
data:
  configuration.yml: |
    theme: light
    default_2fa_method: totp

    log:
      level: debug

    server:
      address: tcp://0.0.0.0:9091/

    authentication_backend:
      file:
        path: /config/users.yml

    session:
      name: authelia_session
      expiration: 3600
      inactivity: 300
      domain: accio.localhost

    storage:
      encryption_key: {{ .Values.authelia.config.encryptionKey }}
      local:
        path: /config/db.sqlite3

    notifier:
      disable_startup_check: true
      filesystem:
        filename: /config/emails.txt

    access_control:
      default_policy: one_factor

    identity_validation:
      reset_password:
        jwt_secret: {{ .Values.authelia.config.sessionSecret }}

    identity_providers:
      oidc:
        hmac_secret: {{ .Values.authelia.config.hmacSecret }}
        jwks:
          - key: |
              ${AUTHELIA_JWKS_PRIVATE_KEY}
        cors:
          endpoints:
            - authorization
            - token
            - revocation
            - introspection
            - userinfo
          allowed_origins:
            - http://accio.localhost:3000
          allowed_origins_from_client_redirect_uris: true
        clients:
          - client_id: accio-portal
            client_name: Accio Portal
            public: true
            authorization_policy: one_factor
            redirect_uris:
              - http://accio.localhost:3000/callback
            scopes:
              - openid
              - profile
              - email
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: none
  users.yml: |
    users:
      admin:
        displayname: "Accio Admin"
        password: "$argon2id$v=19$m=65536,t=3,p=4$9ymXpqyLymoXrc8HYA3Rxw$wLZuT//nvzPk0yuXyOo4t13G+imzLst1P8B7xo2B5PE"
        email: admin@accio.dev
        groups:
          - admins
          - dev