apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-configmap
  namespace: {{ include "accio.namespace" . }}
data:
  configuration.yml: |
    theme: light
    default_2fa_method: totp

    log:
      level: debug

    server:
      address: "tcp://0.0.0.0:9091/"

    authentication_backend:
      file:
        path: /config/users.yml

    session:
      name: authelia_session
      expiration: 3600
      inactivity: 300
      cookies:
        - domain: accio.localhost
          authelia_url: https://accio.localhost:9091

    storage:
      encryption_key: {{ .Values.authelia.config.encryptionKey }}
      local:
        path: /config/db.sqlite3

    notifier:
      disable_startup_check: true
      filesystem:
        filename: /config/emails.txt

    access_control:
      default_policy: one_factor

    identity_validation:
      reset_password:
        jwt_secret: {{ .Values.authelia.config.sessionSecret }}

    identity_providers:
      oidc:
        hmac_secret: {{ .Values.authelia.config.hmacSecret }}
        jwks:
          - key: |
              -----BEGIN PRIVATE KEY-----
              MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDZCED8kXw6Ksve
              OJbfs0s+BiwKYsLIoQC/Q/7EuzlOAq1mN6Cpto8T/6uy8erGC2kLfqTgxGfbZ43/
              GT0euhmqOEBrd/KF8CMGdD4IpzdCNLSOmYRbGmoyhkl2cGgBYG2k8UUu47IHqsW8
              ujr5asGc+QsDzVwLxC/djRohMPbqsmL9Wwly8xfen5s8A1nxbGe+WqS0DssIszLI
              oPBVGGb8edRNgFLCf+2KQr/R+ZZumktJumxLy+MgKsxwY3ZsNr6mOINDtsCiBUd4
              +LF7H/2cEbwpeZwqTNQu59b18OJxgDW6oBW6w6/7gKcfZmXLnxMfqEHNLtDzkuMW
              jbe9IPNTAgMBAAECggEANgxxKrUMi+vWg4vyPtmG1nZxB1EbEx3NctR7IQFDPyM5
              jagy0bEOJrvYRaMrhZCX423xn6wp9SDv4uSlLP7Jn3OMz3a6phJslpHiVQNXppw7
              jvu6U3nbkqOQrfdGX3llNNuFEC1SS8iCoAJ851pnxzDaRmMhFikQhos6Q6PPChlX
              V9Dqxc8QjfB4r+kr1HiPreXcq9RxQ6tfG7WhBTZyoLQ9Ub+Ake7etXAp1gQ9AtFP
              5GVqQQPcjLweh08kGDjUma8lrIbJdyHuO4Ow3oTDCw6sFdvQdR8FS7e8s/e8cJ+M
              WIcAIAT/4GuvicLsYG8Mn+Kf7cAOO2Q6Ox6qQdd/6QKBgQDtSr1eWPgnqWk0sn4x
              xazkB2oPgj/8xt/vzVkGEW35NTqcC4M2qGlfD0hCicrptYyzWMwHJbwVuylPGLOV
              bSJWH3z/q7hk3YQGWxVTn6D35o6Pn4vHPFjwAtq1F7EQ0FDmlggEnTurjROOKLOM
              wbqHMd47WsziPjFY3zVh+Aa6nwKBgQDqJJzX7zV8Yy+NSiNU6Th2K8VsbuqBJXjO
              1J7o+wkPkec9j0Hih6yrrn21WqiQmSTkCQDcug0EZMKSWqgfv2YFk0TdXasZ1+7L
              fFCf36SUbrqij/wxzaIqDeNPA98YyctU2ekqVkdhOBVawazOiiETR0kgTlaDihkY
              ae6MIJU+zQKBgQCKBMnmoasdLp2ByDw8aPTp4SIgiSr8tRQ1n+Qi8mpb5EkF0HBu
              j0BSyUnHYexDSZTgEEsD8T/YB/e8COsTg9nP7BrBfzkOegW7yKi77gIrjs/m2+7q
              YMB+QbrCUFhuJiyYIjXhsS6u1qzEKApfWaNL1YakUWkQQwpi3dln9WK8kwKBgHno
              OilLiKOM2NNNiHvLOfR88bt1PG+lXPMDTQGswpjytF0e24TgcwyoOxdTbnRq6AQ6
              k9JYpDJna87bmLF+69V3SeGfxVgdT11vCmNTA9Osm0vMf9hGYmpW9MTNFTlIx68U
              DgxXA68gji3ErP6UeIgbE33Yi77NBifp76PRyyL5AoGBAJu7b68dq7x93VjL9q7R
              CHeEjub2QFyxRnVC1DOcnULx6h2LN57pvCLwQu5RfBGhDDSilseRsMCmeU2SndwH
              ABxT6nyO5Wg5ZmeuC4uLRpgUCFq1eAlxa0i+tbNc0COjV7lcXiBkHpWkhmex1pEf
              Z1aatAeNCAmOTLPzv2Ng8SES
              -----END PRIVATE KEY-----
        cors:
          endpoints:
            - authorization
            - token
            - revocation
            - introspection
            - userinfo
          allowed_origins:
            - http://accio.localhost:3000
          allowed_origins_from_client_redirect_uris: true
        clients:
          - client_id: accio-portal
            client_name: Accio Portal
            public: true
            authorization_policy: one_factor
            redirect_uris:
              - http://accio.localhost:3000/callback
            scopes:
              - openid
              - profile
              - email
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: none
  users.yml: |
    users:
      admin:
        displayname: "Accio Admin"
        password: "$argon2id$v=19$m=65536,t=3,p=4$9ymXpqyLymoXrc8HYA3Rxw$wLZuT//nvzPk0yuXyOo4t13G+imzLst1P8B7xo2B5PE"
        email: admin@accio.dev
        groups:
          - admins
          - dev